### ISSUE TITLE
可以集成到react-native？

### ISSUE THREAD

**Issue by 401537200** [tianshaokai/AndroidMathKeyboard#2]
最近在研究公式键盘，不过项目是react-native的，目前还未成功，不知道作者有没有这方面的研究？

**Comment by tianshaokai** [comment]
http://mathquill.com/  可以用来编辑公式
https://katex.org/        可以用来显示公式
并没有尝试过，你自己尝试一下，看是否可以解决你的问题

**Comment by 401537200** [comment]
> http://mathquill.com/ 可以用来编辑公式
> https://katex.org/ 可以用来显示公式
> 并没有尝试过，你自己尝试一下，看是否可以解决你的问题

好的，感谢回复，我研究研究。

**Comment by tianshaokai** [comment]
可以看看一起作业他们是如何解决的，他们也有latex

**Comment by tianshaokai** [comment]
@401537200  你对react native熟悉吗，最近入职一家公司也是让用这个，还不会学习，想请教你几个问题

**Comment by 401537200** [comment]
> @401537200 你对react native熟悉吗，最近入职一家公司也是让用这个，还不会学习，想请教你几个问题

我也没接触多久，可以一起探讨一下。
