### ISSUE TITLE
一个小的细节错误

### ISSUE THREAD

**Issue by Martin-zhq** [tianshaokai/AndroidMathKeyboard#3]
布局文件中的MyArcView导包错误了老哥

**Comment by tianshaokai** [comment]
哈哈谢谢了，好久没有关注这个项目了，我修改一下

**Comment by tianshaokai** [comment]
已经修改了，你们也做这种键盘吗，如果有更好的解决latex转换和键盘的方案，希望可以开源出来大家一起学习
